### ISSUE TITLE
Other ordinals than First and Last

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/Documentation#51]
Cf. https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/95#issuecomment-72521874

I don't see any way to describe a question such as "Who is the fourth president of the United States?" with the current datamodel.

We should add an operator for this.

Two alternatives:

* `Nth(l,n)` returns the `n`-th element of the list `l`.
* `Minus(l1,l2)` returns the list containing the elements of `l1` which are not in `l2`.

We have `Nth(l,4) = First(Minus(Minus(Minus(l,First(l)),First(l)),First(l)))`.

**Comment by yhamoudi** [comment]
> We have Nth(l,4) = First(Minus(Minus(Minus(l,First(l)),First(l)),First(l))).

No way!

**Comment by ProgVal** [comment]
+1 for Nth

**Comment by Ezibenroc** [comment]
Yes I find it very ugly, and this might trigger huge communications if one user ask for the billionth item.
But the operator `Minus` is more general and could be usefull in other cases.

**Comment by Tpt** [comment]
My 2 cents:
- "But the operator Minus is more general and could be usefull in other cases." Yes, but in our use case it may create very long trees (example: "Who is the 29th president of the United States?"). Do we want such trees? So, I think we may pay the cost of having two nodes (Minus and Nth).
-  I don't like the name "Nth" (that is imho a little bit not clear). But I would like to avoid "at position". Does someone have a better name?

**Comment by Ezibenroc** [comment]
> I don't like the name "Nth"

This is the name used in [OCaml](http://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html) and [Erlang](http://erlang.org/doc/man/lists.html#nth-2)!

**Comment by Tpt** [comment]
I'm not sure that these two languages have the best readability. It's not because some other people do something that this thing is good.

**Comment by s-i-newton** [comment]
I think the two operators are useful, but not now. Wa can add the minus 
later if needed...

And I like the name nth, it is much more popular in english than the two 
examples can make think and, indeed, it is very clear.

**Comment by yhamoudi** [comment]
This issue was still opened here: https://github.com/ProjetPP/Documentation/issues/35

Here's what it says (i closed the issue):

    position(l, i) should returns the ith element of l.
    First(l) would became an alias for position(l, 1) et last(l) one of position(l, -1).

**Comment by Tpt** [comment]
I think we all agree on the use cases of the operators.

Two questions remain:

1. Position(l, i) or Nth(l, i)? 
2. Should we tag First and Last as deprecated in order to remove them in the future or should we keep them indefinitely as aliases of position(, 1) and position(, -1)? (in both cases, datamodel libs may do some normalization in order to allow modules to don't have to deal with the two writing of the same thing).

**Comment by ProgVal** [comment]
1. Nth. Position is ambiguous (it could be the index of an item of the
list).
I would also prefer Nth(i, l) because the list could possibly be very
long and it would be less readable to have the index after it.

2. Yes, I think we should make them deprecated.

**Comment by Ezibenroc** [comment]
@ProgVal: +1
